version: '3.4'
services:
  # back-end api built with golang
  golang-prod:
    restart: always
    build: 
      context: golang
      target: prod
    network_mode: host
    ports:
      - "5000:5000"
    env_file: .env

  # front-end built with react
  react-prod:
    restart: always
    build: 
      context: react
      target: prod
    network_mode: host
    ports:
      - "3000:3000"

  # nginx is used for ssl termination
  nginx-prod:
    restart: always
    build: 
      context: nginx
      target: prod
    # volumes:
    #  - ../certs-data:/data/letsencrypt
    #  - /etc/letsencrypt/:/etc/letsencrypt/
    network_mode: host
    ports:
      - "80:80"
      - "443:443"