version: '3'
services:
  golang:
    build: golang
    volumes:
      - ./golang:/go/src/github.com/karlkeefer/pngr/golang
    ports:
      - "5000:5000"

  react:
    build: react
    volumes:
      - ./react:/root
    ports:
      - "3000:3000"

  # postgres is our primary data store
  psql:
    image: "postgres:10.4-alpine"

  # nginx is used for ssl termination
  nginx:
    build: nginx
    ports:
      - "443:443"