version: '3'
services:
  back:
    build: back
    volumes:
      - ./back:/root
    ports:
      - "5000:5000"

  front:
    build: front
    volumes:
      - ./front:/root
    ports:
      - "3000:3000"

  # postgres is our primary data store
  psql:
    image: "postgres:10.4-alpine"

  # nginx is used for ssl termination
  nginx:
    build: nginx
    ports:
      - "443:443"