version: '3'
services:
  golang:
    build: golang
    volumes:
      - ./golang:/go/src/github.com/karlkeefer/pngr/golang
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  react:
    build: react
    volumes:
      - ./react:/root
    ports:
      - "3000:3000"

  # postgres is our primary data store
  postgres:
    image: "postgres:10.4-alpine"

  # nginx is used for ssl termination
  nginx:
    build: nginx
    ports:
      - "443:443"