version: '3'
services:
  # back-end api built with golang
  golang:
    build: golang
    volumes:
      - ./golang:/pngr/golang
    ports:
      - "5000:5000"
    environment:
      - APP_ROOT=https://localhost
      - TOKEN_SECRET=asd973hkalkjhx97asdh
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  # front-end built with react
  react:
    build: react
    volumes:
      - ./react:/root
    ports:
      - "3000:3000"

  # postgres is our primary data store
  postgres:
    build: postgres
    volumes:
      - ./postgres/migrations:/docker-entrypoint-initdb.d/migrations

  # nginx is used for ssl termination
  nginx:
    build: nginx
    ports:
      - "443:443"